apiVersion: v1
kind: Namespace
metadata:
  name: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
  labels:
    app: flask
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
      name: flask
    spec:
      containers:
      - image: flask-demo:latest
        name: flask
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      nodeSelector:
        type: worker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-service
  name: flask-service
  namespace: flask
spec:
  ports:
  - name: 8080-5000
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: ClusterIP