apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-service
  name: flask-service
  namespace: flask
spec:
  ports:
  - name: 8080-5000
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: ClusterIP