apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flask
  name: flask
  namespace: flask
spec:
  containers:
  - image: flask-demo:latest
    name: flask
    ports:
    - containerPort: 5000
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    type: worker

